-- ============================================================
-- MANTER PROJETO ATIVO
-- ============================================================

-- 1. INFORME OS DADOS DO PROJETO

create or replace function public.dados_manter_ativo()
returns table (url text, chave text)
language sql
as $$
    select
        'https://onhqfqnflyojqsizoehdafadp.supabase.co/rest/v1/',
        'sb_publishable_Yy0iudsdadtMn2KtWcx-r_YSuYw_np-UiBn3';
$$;


-- ============================================================
-- 2. EXTENSOES
-- ============================================================

-- Agenda execucoes e permite requisicoes HTTP.
create extension if not exists pg_cron;
create extension if not exists pg_net;


-- ============================================================
-- 3. TABELA DE MANUTENCAO
-- ============================================================

create table if not exists public.manter_ativo (
    id bigint generated by default as identity primary key,
    mensagem text not null default 'Projeto ativo'
);

insert into public.manter_ativo (mensagem)
select 'Projeto ativo'
where not exists (
    select 1 from public.manter_ativo
);


-- ============================================================
-- 4. SEGURANCA
-- ============================================================

alter table public.manter_ativo enable row level security;

grant select on public.manter_ativo to anon;

drop policy if exists manter_ativo_select
on public.manter_ativo;

create policy manter_ativo_select
on public.manter_ativo
for select
to anon
using (true);


-- ============================================================
-- 5. FUNCAO DE MANUTENCAO
-- ============================================================

create or replace function public.manter_banco_ativo()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    supabase_url text;
    publishable_key text;
begin

    select url, chave
    into supabase_url, publishable_key
    from public.dados_manter_ativo();

    perform net.http_get(
        url := supabase_url ||
               '/rest/v1/manter_ativo?select=id&limit=1',

        headers := jsonb_build_object(
            'apikey', publishable_key
        )
    );

end;
$$;


-- ============================================================
-- 6. AGENDAMENTO
-- ============================================================

-- Remove o anterior, caso exista.
select cron.unschedule('keep-alive-supabase')
where exists (
    select 1
    from cron.job
    where jobname = 'keep-alive-supabase'
);

-- Executa uma vez por dia.
select cron.schedule(
    'keep-alive-supabase',
    '0 6 * * *',
    'select public.manter_banco_ativo();'
);


-- ============================================================
-- 7. VERIFICAR
-- ============================================================

select jobname, schedule, active
from cron.job
where jobname = 'keep-alive-supabase';
